# This manifest creates a service for the Servian TechApp pods 
apiVersion: v1
kind: Service
metadata:
  name: servian-techchallengeapp
  namespace: servian
  labels:
    app: servian
spec:
  type: ClusterIP
  ports:
  - name: tcp3000
    port: 3000
    targetPort: 3000
  selector:
    app: servian