apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  namespace: servian
  name: database-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi