apiVersion: v1    
kind: Secret
metadata:
  name: app-secret
  namespace: servian
type: Opaque
data:
  VTT_DBUSER: cG9zdGdyZXM=  ###base64 encoded
  VTT_DBPASSWORD: Y2hhbmdlbWU= ###base64 encoded
  VTT_DBNAME: YXBw ###base64 encoded